// ⚠️ Auto-generated by scripts/generate-news-posts.js — do not edit manually

import post0 from '@/content/_posts/news/testing-a-default-blogpost.md';

export const newsPosts = [
  {
    slug: 'testing-a-default-blogpost',
    ...post0.attributes,
    Component: post0.react,
  }
];
