import Menubar from '@/components/menubar';
import localFont from 'next/font/local';
import './globals.css';
import Head from 'next/head';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <Head>
        <script src='https://identity.netlify.com/v1/netlify-identity-widget.js' />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menubar />
        {children}
      </body>
    </html>
  );
}
